version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: serde
    versions:
    - 1.0.113
    - 1.0.118
  - dependency-name: tokio
    versions:
    - 1.0.1
    - 1.1.1
  - dependency-name: structopt
    versions:
    - 0.3.21
  - dependency-name: warp
    versions:
    - 0.2.5
